on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  call-workflow:
    uses: yukihiko-shinoda/invoke-lint/.github/workflows/reusable-deploy.yml@main
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
