on:
  push:
    branches:
      - main
# For OIDC token exchange with Qlty:
# - Configuring OpenID Connect in cloud providers - GitHub Docs
#   https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers#adding-permissions-settings
permissions:
  contents: read
  id-token: write
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y ffmpeg
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.14'
      - run: uv sync
      - run: uv run invoke test.coverage --xml
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage.xml
          format: cobertura
          add-prefix: 'asyncffmpeg/'
